Add support to pre-epoch Unix time
JamesNK/Newtonsoft.Json pull request #2614
Opened 2021-11-17 21:19 UTC by MaxKot

Fixes #2292

The existing implementation contains code specifically to disallow dates before Unix epoch. It can be assumed that some users of the library depend on the converter throwing an exception if such date is serialized or deserialized. To maintain backwards compatibility, a constructor parameter and a property are introduced to explicitly enable the new behavior. A static default setting for allowing pre-epoch dates was also introduced to help library users to switch to the new behavior with minimal changes of the client code.

### Rationale

Many implementations of Unix time use signed integer values with negative values representing dates before Unix epoch. Examples of such implementations are some C standard libraries and DateTimeOffset.ToUnixTimeSeconds and DateTimeOffset.FromUnixTimeSeconds methods in .NET basic class library. JavaScript built-in Date.prototype.getTime() method type uses milliseconds instead of seconds but it still handles pre-epoch dates with negative numbers. In fact the only implementation disallowing pre-epoch dates I could find was MySQL. Hence negative timestamps are likely to appear in JSON documents in any problem domain that handles dates before 1970-01-01 (e.g. people birthdays).

2022-02-07 19:54 UTC, MaxKot commented
@JamesNK could you please take look at this?

2022-02-07 19:58 UTC, JamesNK requested changes
This looks fine apart from static configuration.

2022-02-07 19:58 UTC, JamesNK commented on Src/Newtonsoft.Json/Converters/UnixDateTimeConverter.cs
> +        public static bool DefaultAllowPreEpoch { get; set; } = false;
Static configuration like this isn't desirable. It is global and different apps/libraries can override each other. Please remove.

2022-02-07 21:58 UTC, MaxKot commented
Thanks for the quick reply!

> Static configuration like this isn't desirable. It is global and different apps/libraries can override each other. Please remove.

Done.

2022-04-22 14:15 UTC, BrandonDusseau commented
@JamesNK would you mind taking another look at this? Having the ability to parse pre-1970 dates from epoch time would be immensely helpful. I would even go as far as to enable it without an option.

2022-05-15 14:31 UTC, JamesNK approved these changes

2022-05-15 14:43 UTC, merged

2022-05-15 14:44 UTC, JamesNK commented
Thanks!